# Generated by Django 5.0.6 on 2024-06-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=20, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Фотография')),
            ],
        ),
    ]
