# Generated by Django 5.0.6 on 2024-06-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='header',
            new_name='heading',
        ),
    ]
