# Generated by Django 5.0.6 on 2024-06-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_header_about_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='about',
            name='heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок'),
        ),
    ]
