# Generated by Django 5.0.6 on 2024-06-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_about_description_alter_about_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, max_length=600, verbose_name='Описание'),
        ),
    ]
