# Generated by Django 5.0.6 on 2024-06-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_about_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, max_length=600, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Фотография')),
            ],
        ),
    ]
