# Generated by Django 5.0.6 on 2024-06-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_aboutrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('image_1', models.ImageField(upload_to='rooms/', verbose_name='Фотография')),
                ('image_2', models.ImageField(upload_to='rooms/', verbose_name='Фотография')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка')),
                ('wifi', models.BooleanField(default=True)),
            ],
        ),
    ]
