# Generated by Django 5.0.6 on 2024-06-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Номера'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='wifi',
        ),
        migrations.AddField(
            model_name='room',
            name='base_advatages',
            field=models.BooleanField(default=True, verbose_name='Базовые преимущества'),
        ),
        migrations.AddField(
            model_name='room',
            name='large_bed',
            field=models.BooleanField(default=False, verbose_name='Королевская кровать'),
        ),
        migrations.AddField(
            model_name='room',
            name='type_of_room',
            field=models.CharField(choices=[('HOSTEL', 'Хостел'), ('MINI-HOTEL', 'Мини-отель')], default='HOSTEL', max_length=15, verbose_name='Тип комнаты'),
        ),
    ]
