# Generated by Django 5.0.6 on 2024-06-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_room_options_remove_room_wifi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='short_descriptio',
            field=models.TextField(default=1, verbose_name='Короткое описание'),
            preserve_default=False,
        ),
    ]
