# Generated by Django 5.0.6 on 2024-06-29 09:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_roomnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime.today)),
                ('end_date', models.DateField(default=datetime.datetime.today)),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.roomnumber')),
            ],
            options={
                'verbose_name': 'Бронирование',
            },
        ),
    ]
