# Generated by Django 5.0.6 on 2024-07-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_booking_capacity_roomnumber_full_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('UNCONFIRMED', 'UNCONFIRMED'), ('CONFIRMED', 'CONFIRMED'), ('CANCELED', 'CANCELED')], default='UNCONFIRMED', max_length=15, verbose_name='Статус бронирования'),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
