# Generated by Django 5.0.6 on 2024-07-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_custumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutrooms',
            name='link',
            field=models.TextField(default=1, verbose_name='LINK'),
            preserve_default=False,
        ),
    ]
